spring.application.name=chatbot

spring.datasource.url=jdbc:mysql://localhost:3306/gameaidb
spring.datasource.username=root
spring.datasource.password=16102004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

openrouter.api-key=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
openrouter.model=openai/gpt-3.5-turbo
