spring.application.name=chatbot

spring.datasource.url=jdbc:mysql://localhost:3306/gameaidb
spring.datasource.username=root
spring.datasource.password=16102004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

openrouter.api-key=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
openrouter.model=openai/gpt-3.5-turbo